i2c: convert to struct i2c_driver::probe_new() (prepare for v6.3 kernel)
Upstream kernel commit [1] has switched probe() to the same
signature as probe_new(), which breaks compilation for the
drivers here:
.../common/../private/google-modules/amplifiers/drv2624/drv2624.c:1903:11: error: incompatible function pointer types initializing 'int (*)(struct i2c_client *)' with an expression of type 'int (struct i2c_client *, const struct i2c_device_id *)' [-Wincompatible-function-pointer-types]
        .probe = drv2624_i2c_probe,
                 ^~~~~~~~~~~~~~~~~
1 error generated.

The probe function doesn't make use of the i2c_device_id * parameter so
it can be trivially converted.

[1] https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=03c835f498b5
    ("i2c: Switch .probe() to not take an id parameter")

Bug: 277308451
Test: TH
Change-Id: I73f438c8189ea5048a570276d6fa4cb24a31e077
Signed-off-by: André Draszik <draszik@google.com>
Signed-off-by: Will McVicker <willmcvicker@google.com>