google_cpm: usb_types is a bitmask now (v6.12 compat)
Linux commit [1] has changed struct power_supply_desc::usb_types from
enum power_supply_usb_type to u32 (and removed struct
power_supply_desc::num_usb_types accordingly).

This causes this driver to fail to compile:
    .../google_cpm.c:4404:15: error: incompatible pointer to integer conversion initializing 'u32' (aka 'unsigned int') with an expression of type 'enum power_supply_usb_type[2]' [-Wint-conversion]
     4404 |         .usb_types      = gcpm_pps_usb_types,
          |                           ^~~~~~~~~~~~~~~~~~
    .../google_cpm.c:4405:3: error: field designator 'num_usb_types' does not refer to any field in type 'const struct power_supply_desc'; did you mean 'usb_types'?
     4405 |         .num_usb_types  = ARRAY_SIZE(gcpm_pps_usb_types),
          |          ^~~~~~~~~~~~~
          |          usb_types
    .../common/include/linux/power_supply.h:252:6: note: 'usb_types' declared here
      252 |         u32 usb_types;
          |             ^

Update the driver accordingly.

Link: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=364ea7ccaef9 [1]
      ("power: supply: Change usb_types from an array into a bitmask")
Test: TH
Bug: 369476437
Change-Id: I3a573527c100d3a875882d044df69beb7ab93066
Signed-off-by: André Draszik <draszik@google.com>