google_battery: fix printf format
bms/google_battery.c:2254:4: error: format specifies type 'long' but the argument has type 'ktime_t' (aka 'long long') [-Werror,-Wformat]
 2247 |         logbuffer_log(log, "S: %hu,%hu, %hu,%hu %hu,%hu %ld,%ld, %u",
      |                                                         ~~~
      |                                                         %lld
 2248 |                         ce_data->charging_stats.ssoc_in,
 2249 |                         ce_data->charging_stats.voltage_in,
 2250 |                         ce_data->charging_stats.ssoc_out,
 2251 |                         ce_data->charging_stats.voltage_out,
 2252 |                         ce_data->charging_stats.cc_in,
 2253 |                         ce_data->charging_stats.cc_out,
 2254 |                         ce_data->first_update,
      |                         ^~~~~~~~~~~~~~~~~~~~~
bms/google_battery.c:2255:4: error: format specifies type 'long' but the argument has type 'ktime_t' (aka 'long long') [-Werror,-Wformat]
 2247 |         logbuffer_log(log, "S: %hu,%hu, %hu,%hu %hu,%hu %ld,%ld, %u",
      |                                                             ~~~
      |                                                             %lld
 2248 |                         ce_data->charging_stats.ssoc_in,
 2249 |                         ce_data->charging_stats.voltage_in,
 2250 |                         ce_data->charging_stats.ssoc_out,
 2251 |                         ce_data->charging_stats.voltage_out,
 2252 |                         ce_data->charging_stats.cc_in,
 2253 |                         ce_data->charging_stats.cc_out,
 2254 |                         ce_data->first_update,
 2255 |                         ce_data->last_update,
      |                         ^~~~~~~~~~~~~~~~~~~~

Fixes: cced17c4ee20 ("google_battery: add charge details into logbuffer")
Test: TH
Bug: 348164658
Signed-off-by: André Draszik <draszik@google.com>
(cherry picked from https://partner-android-review.googlesource.com/q/commit:485b004702d98ea2cda179d0581739d1ebd10e2b)
Merged-In: Ibd2a9d5aadd79a16639524f4ea87c0c84fdc8d55
Change-Id: Ibd2a9d5aadd79a16639524f4ea87c0c84fdc8d55
(cherry picked from commit ed8eeef62625710a846de1497a4b6507fb51a523)