rt9471_charger: fix flags in gpio_request() (v6.12 prep)
Linux commits [1] and [2] have cleaned up gpio flags and GPIOF_INIT_*
and GPIOF_DIR_* are gone. Drivers are meant to use GPIOF_OUT_INIT_* for
output gpios instead (and were required to do so for a long time).

This causes this driver to fail to compile:
    .../rt9471_charger.c:1411:29: error: use of undeclared identifier 'GPIOF_DIR_OUT'
     1411 |         unsigned long init_flags = GPIOF_DIR_OUT;
          |                                    ^
    1 error generated.

The code in here either sets init_flags to GPIOF_DIR_OUT or to
GPIOF_OUT_INIT_HIGH (a bit further down). Given that, and given
GPIOF_DIR_OUT == 0, using GPIOF_OUT_INIT_LOW instead should be the
correct fix. Update the code accordingly.

Link: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=4b2b0a2ce815 [1]
      ("gpiolib: legacy: Kill GPIOF_INIT_* definitions")
Link: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=8c045ca534d0 [2]
      ("gpiolib: legacy: Kill GPIOF_DIR_* definitions")
Test: TH
Bug: 369317190
Change-Id: Ib92b2103acae328768c3a68087ff7318fefe886b
Signed-off-by: André Draszik <draszik@google.com>
(cherry picked from commit 05cb45323c5b71c0180521b16fcc809126e65fa9)