max77729_pmic: fix confusion around max77759-gpio direction (v6.12 prep)
Linux commit [1] has removed GPIOF_DIR_OUT and GPIOF_DIR_IN.

This causes this OOT Pixel driver to fail compilation:
    .../max77729_pmic.c:945:14: error: use of undeclared identifier 'GPIOF_DIR_OUT'
      945 |                 if (dir != GPIOF_DIR_OUT)  {
          |                            ^
    .../max77729_pmic.c:953:14: error: use of undeclared identifier 'GPIOF_DIR_OUT'
      953 |                 if (dir != GPIOF_DIR_OUT)  {
          |                            ^
    2 errors generated.

It also highlights incorrect use of this flag to retrieve and mask
register values. The Linux flag GPIOF_DIR_OUT has nothing to do with
the hardware bits 2 and 5 of the max77759 'GPIO Control Read' command.
We should mask the correct bits here, using the appropriate macros.
Bits 2 or 5 are set to 1 if the direction is output, and to 0 if
direction is input.

Let's fix this obvious bug and in preparation of that kernel change,
switch to using the correct macros.

Link: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=8c045ca534d0 [1]
      ("gpiolib: legacy: Kill GPIOF_DIR_* definitions")
Test: TH
Bug: 369317190
Change-Id: Ie111aa83fe94bedb2fbe07fbf2d5940261c6faee
Signed-off-by: André Draszik <draszik@google.com>
(cherry picked from commit 2bb95bbe36b9b192a012386ef13fd3c6408905c8)